apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      containers:
        - name: karakeep
          image: ghcr.io/yaelmoshi/karakeep:postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: karakeep-postgres-app
                  key: uri
          envFrom:
            - configMapRef:
                name: karakeep-configuration
            - secretRef:
                name: karakeep-secrets
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
