#!/command/with-contenv sh
# shellcheck shell=bash

cd /app/apps/workers;
if [ "${USE_JEMALLOC:-false}" = "true" ]; then
    export LD_PRELOAD=/usr/local/lib/libjemalloc.so
fi
exec node dist/index.mjs
